# permissions for end users to edit gogatekeepers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gogatekeeper-editor-role
rules:
- apiGroups:
  - gatekeeper.adstein
  resources:
  - gogatekeepers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gatekeeper.adstein
  resources:
  - gogatekeepers/status
  verbs:
  - get
