# permissions for end users to view gogatekeepers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gogatekeeper-viewer-role
rules:
- apiGroups:
  - gatekeeper.theendbeta.me
  resources:
  - gogatekeepers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gatekeeper.theendbeta.me
  resources:
  - gogatekeepers/status
  verbs:
  - get
