apiVersion: v1
kind: Secret
metadata:
  name: gatekeeper-secret
stringData:
  PROXY_CLIENT_SECRET: ZXhhbXBsZS1hcHAtc2VjcmV0
  PROXY_ENCRYPTION_KEY: VtMkufTWXWA5x83C
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatekeeper-env
data:
  PROXY_CLIENT_ID: example-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gk
  labels:
    app: nginx-gk-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-gk-test
  template:
    metadata:
      labels:
        app: nginx-gk-test
      annotations:
        gatekeeper.gogatekeeper: gatekeeper-test
        gatekeeper.gogatekeeper/existingSecretEnv: gatekeeper-secret
        gatekeeper.gogatekeeper/existingEnv: gatekeeper-env
        # Edit these annotations
        gatekeeper.gogatekeeper/redirection-url: "http://10.176.128.136:30001"
    spec:
      containers:
      - name: nginx
        image: nginx:stable
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gk
  labels:
    app: nginx-gk-test
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30001
    protocol: TCP
    name: http
  selector:
    app: nginx-gk-test
