apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx-no-gk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-no-gk
  template:
    metadata:
      labels:
        app: nginx-no-gk
    spec:
      containers:
      - name: nginx
        image: nginx:stable
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx-no-gk
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
    name: http
  selector:
    app: nginx-no-gk
